### Find All
GET http://localhost:3000/internal/api/categories
Accept: application/json

### Create
POST http://localhost:3000/internal/api/categories
Accept: application/json
Content-Type: application/json

{
  "name": "test_baru",
  "desc": "test_baru"
}

### Get By Id
GET http://localhost:3000/internal/api/categories/2
Accept: application/json

### Update
PUT http://localhost:3000/internal/api/categories/2
Accept: application/json
Content-Type: application/json

{
  "name": "qweq",
  "desc": "test_update"
}

### Delete
DELETE http://localhost:3000/internal/api/categories/4
Accept: application/json
